export enum ActionType {
    SIGN_IN = "PROFILE::SIGN_IN",
    SIGN_OUT = "PROFILE::SIGN_OUT",
    CHANGE_DEFAULT_CATEGORY = "PROFILE::CHANGE_DEFAULT_CATEGORY",
    CHANGE_LANGUAGE = "PROFILE::CHANGE_LANGUAGE",
    MERGE = "PROFILE::MERGE",
}
